/**
 * The example network.
 *
 * A blank canvas is the worst possible first screen for a tool like this: you cannot
 * tell what a finished map is supposed to look like, so you cannot tell what any of the
 * controls are for. Opening a small finished network first answers both questions in a
 * second, and gives you something safe to poke at.
 *
 * Deliberately small — five lines, one branch, one river — but it uses every idea in the
 * app: a shared corridor with parallel offsets, bar interchanges, a Y-shaped branch,
 * multiple modes, and a river simplified between the two views.
 */

import { newBranchId, newLineId, newProjectId, newStationId, newTerrainId } from './ids'
import { createEmptyProject } from './defaults'
import type { Branch, Line, Project, Station, StationId, Terrain, Vec2 } from './types'

interface Seed {
  name: string
  /** Diagram position. The geographic position is derived by nudging this around. */
  at: Vec2
}

/**
 * Geographic positions are generated by pushing each station off its tidy diagram
 * position, so the two spaces genuinely differ and "show true position" has something
 * to show. Deterministic, so the example is identical every time.
 */
function scatter(p: Vec2, i: number): Vec2 {
  const a = Math.sin(i * 12.9898) * 43758.5453
  const b = Math.sin(i * 78.233) * 12345.6789
  const jitterX = ((a - Math.floor(a)) - 0.5) * 90
  const jitterY = ((b - Math.floor(b)) - 0.5) * 90
  return { x: Math.round(p.x + jitterX), y: Math.round(p.y + jitterY) }
}

export function createSampleProject(): Project {
  const base = createEmptyProject('Aldbury — example network')
  base.id = newProjectId()

  let seq = 0
  const byName = new Map<string, StationId>()

  const place = (seed: Seed): Station => {
    const id = newStationId()
    byName.set(seed.name, id)
    seq++
    return {
      id,
      name: seed.name,
      schematic: { ...seed.at },
      geo: scatter(seed.at, seq),
      modes: [],
      label: { anchor: 'auto', offset: { x: 0, y: 0 }, pinned: false, angle: 0, hidden: false },
    }
  }

  // A grid of 40 keeps every seeded segment octilinear from the start.
  const seeds: Seed[] = [
    // East–west trunk, which several services share.
    { name: 'Westgate', at: { x: 120, y: 360 } },
    { name: 'Mill Road', at: { x: 240, y: 360 } },
    { name: 'Cathedral', at: { x: 360, y: 360 } },
    { name: 'Central', at: { x: 480, y: 360 } },
    { name: 'Market', at: { x: 600, y: 360 } },
    { name: 'Eastfield', at: { x: 760, y: 360 } },

    // North–south line crossing at Central.
    { name: 'Northgate', at: { x: 480, y: 160 } },
    { name: 'The Park', at: { x: 480, y: 240 } },
    { name: 'Riverside', at: { x: 480, y: 480 } },
    { name: 'Docks', at: { x: 480, y: 600 } },

    // The Y branch off the trunk, splitting at Market.
    { name: 'Hillcrest', at: { x: 720, y: 240 } },
    { name: 'Airport', at: { x: 800, y: 160 } },
    { name: 'Quayside', at: { x: 720, y: 480 } },

    // Tram loop in the west.
    { name: 'Old Town', at: { x: 240, y: 240 } },
    { name: 'University', at: { x: 120, y: 240 } },

    // Ferry pier.
    { name: 'South Pier', at: { x: 360, y: 600 } },
  ]

  const stations = seeds.map(place)
  const id = (name: string): StationId => byName.get(name)!

  const branch = (stops: string[], name?: string): Branch => ({
    id: newBranchId(),
    name,
    stops: stops.map(id),
  })

  const line = (
    name: string,
    mode: string,
    color: string,
    branches: Branch[],
  ): Line => ({
    id: newLineId(),
    name,
    mode,
    color,
    branches,
    bends: {},
    hidden: false,
  })

  const lines: Line[] = [
    // Shares Cathedral -> Market with the tram and the bus, which is what produces the
    // parallel strokes and the bar-shaped interchange symbols.
    line('M1', 'metro', '#C9342B', [
      branch(['Westgate', 'Mill Road', 'Cathedral', 'Central', 'Market', 'Eastfield']),
    ]),

    line('M2', 'metro', '#1B4F9C', [
      branch(['Northgate', 'The Park', 'Central', 'Riverside', 'Docks']),
    ]),

    // A genuine Y: both branches share Cathedral -> Market, then split.
    line('T4', 'tram', '#00784F', [
      branch(['Cathedral', 'Central', 'Market', 'Hillcrest', 'Airport'], 'to Airport'),
      branch(['Market', 'Quayside'], 'to Quayside'),
    ]),

    line('B12', 'bus', '#B45A0E', [
      branch(['University', 'Old Town', 'Cathedral', 'Central', 'Market']),
    ]),

    line('F1', 'ferry', '#0D7C93', [branch(['South Pier', 'Riverside', 'Quayside'])]),
  ]

  // The river: a wandering trace over the map, simplified to three strokes for the
  // diagram — the move that separates a transit map from a drawing on a screenshot.
  const river: Terrain = {
    id: newTerrainId(),
    kind: 'waterway',
    name: 'River Ald',
    geo: [
      { x: 60, y: 520 },
      { x: 180, y: 546 },
      { x: 300, y: 512 },
      { x: 430, y: 556 },
      { x: 560, y: 524 },
      { x: 700, y: 566 },
      { x: 860, y: 534 },
    ],
    schematic: [
      { x: 60, y: 540 },
      { x: 400, y: 540 },
      { x: 520, y: 660 },
      { x: 860, y: 660 },
    ],
    closed: false,
    hidden: false,
  }

  return {
    ...base,
    stations,
    lines,
    terrain: [river],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
}
