/**
 * The example network.
 *
 * A blank canvas is the worst possible first screen for a tool like this: you cannot
 * tell what a finished map is supposed to look like, so you cannot tell what any of the
 * controls are for. Opening a finished network first answers both questions in a second,
 * and gives you something safe to pull apart.
 *
 * It is deliberately a whole city rather than a sketch, because every feature in the app
 * has to be visible in it to be discoverable at all. Between them the lines below
 * exercise: all six transport modes, a Y-shaped branch, a closed ring with no terminus,
 * an express that runs through the stations it skips, a one-way loop, a branch with its
 * own colour and its own service label, shared corridors with parallel offsets, bar
 * interchanges, out-of-station walking links, crossings, fare zones, second names,
 * accessibility marks, stations not yet open, terrain with holes and hatching, styled
 * annotations, and a legend that derives itself from the lines.
 *
 * Everything is laid out on a 60-unit grid so corridors meet at exact coordinates. That
 * is what makes the interchanges real: two lines sharing a point share a station, with
 * no bookkeeping.
 */

import {
  newBranchId,
  newLineId,
  newPlacementId,
  newProjectId,
  newStationId,
  newTerrainId,
  newTransferId,
} from './ids'
import { createEmptyProject, makeBranch, makeStation, makeTerrain } from './defaults'
import type {
  Branch,
  Line,
  Placement,
  Project,
  Station,
  StationId,
  Terrain,
  Vec2,
} from './types'

/**
 * Geographic positions are generated by pushing each station off its tidy diagram
 * position, so the two spaces genuinely differ and "show true position" has something
 * to show. Deterministic, so the example is identical every time.
 */
function scatter(p: Vec2, i: number): Vec2 {
  const a = Math.sin(i * 12.9898) * 43758.5453
  const b = Math.sin(i * 78.233) * 12345.6789
  return {
    x: Math.round(p.x + (a - Math.floor(a) - 0.5) * 110),
    y: Math.round(p.y + (b - Math.floor(b) - 0.5) * 110),
  }
}

/** Centre of the city, used to work out which fare zone a stop falls in. */
const HUB: Vec2 = { x: 720, y: 460 }

function zoneFor(p: Vec2): string {
  const d = Math.max(Math.abs(p.x - HUB.x) / 1.35, Math.abs(p.y - HUB.y))
  if (d <= 250) return '1'
  if (d <= 420) return '2'
  return '3'
}

export function createSampleProject(): Project {
  const base = createEmptyProject('Aldbury — example network')
  base.id = newProjectId()

  const stations: Station[] = []
  const byPoint = new Map<string, StationId>()
  const byName = new Map<string, StationId>()
  let seq = 0

  /**
   * A station at a point, created once.
   *
   * Two corridors quoting the same coordinate get the same station, which is how every
   * interchange on this map comes about — nothing declares them.
   */
  const at = (x: number, y: number, name: string, extra: Partial<Station> = {}): StationId => {
    const key = `${x},${y}`
    const found = byPoint.get(key)
    if (found) {
      if (Object.keys(extra).length > 0) {
        const s = stations.find((q) => q.id === found)!
        Object.assign(s, extra)
      }
      return found
    }
    const id = newStationId()
    seq++
    const st = makeStation(id, name, { x, y }, {
      geo: scatter({ x, y }, seq),
      zone: zoneFor({ x, y }),
      ...extra,
    })
    stations.push(st)
    byPoint.set(key, id)
    byName.set(name, id)
    return id
  }

  /** Evenly spaced stops along a straight run, named from the list. */
  const run = (
    from: Vec2,
    step: Vec2,
    names: (string | [string, Partial<Station>])[],
  ): StationId[] =>
    names.map((entry, i) => {
      const [name, extra] = Array.isArray(entry) ? entry : [entry, {}]
      return at(from.x + step.x * i, from.y + step.y * i, name, extra)
    })

  const P = (x: number, y: number): Vec2 => ({ x, y })

  // -------------------------------------------------------------------------
  // Heavy rail — the outer spine, and the express that overtakes on it
  // -------------------------------------------------------------------------

  const railStops = run(P(120, 100), P(120, 0), [
    ['Aldbury Parkway', { badges: ['rail', 'park-ride', 'step-free'] }],
    'Fenwick',
    'Hollowmere',
    ['Norbridge', { badges: ['rail', 'step-free'] }],
    'Stanmoor',
    ['Aldbury North', { nameSecondary: 'Gogledd Aldbury', badges: ['rail', 'step-free'] }],
    'Kestrel Hill',
    ['Ravensmoor', { badges: ['rail'] }],
    'Thornleigh',
    'Whitcombe',
    ['Eastmarch', { badges: ['rail', 'park-ride'] }],
  ])

  // -------------------------------------------------------------------------
  // Metro
  // -------------------------------------------------------------------------

  const m1 = run(P(120, 460), P(60, 0), [
    ['Westgate', { badges: ['park-ride'] }],
    'Alder Row',
    'Brackenfield',
    'Fairholme',
    ['Guild Cross', { badges: ['step-free'] }],
    'Saltmarket',
    'Cordwainer Lane',
    'Lamplight',
    ['Guild Square', { nameSecondary: 'Sgwâr y Gild', badges: ['step-free'] }],
    'Exchange',
    ['Aldbury Central', { nameSecondary: 'Canol Aldbury', badges: ['rail', 'step-free', 'bus'] }],
    'Threadneedle',
    ['Kings Wharf', { badges: ['ferry'] }],
    'Tanner Street',
    'Ironside',
    'Marsh Lane',
    ['Eastgate', { badges: ['step-free'] }],
    'Bellingford',
    'Crowmere',
    'Havershall',
    ['Eastfield', { badges: ['park-ride'] }],
  ])

  const m2 = run(P(720, 100), P(0, 60), [
    'Aldbury North',
    'Vestry Green',
    ['Highgate Bar', { badges: ['step-free'] }],
    'Pentland',
    'Cloister Walk',
    'Rookwood',
    'Aldbury Central',
    'Bishopsgate',
    ['Southwark Row', { badges: ['step-free'] }],
    'Candlewick',
    'Sallow Bridge',
    'Peartree',
    ['Foundry Fields', { status: 'construction' }],
    ['Aldbury South', { badges: ['park-ride'], status: 'construction' }],
  ])

  const m3 = run(P(240, 820), P(60, -60), [
    ['Millgate', { badges: ['bus'] }],
    'Lowbank',
    'Sedgeley',
    'Carrow',
    'Netherfold',
    'Amberley',
    'Guild Square',
    'Blackfriars',
    'Cloister Walk',
    'Ashcombe',
    'Templeton',
    ['Fallowfield', { status: 'planned' }],
    'Ravensmoor',
  ])

  // A genuine Y. The trunk runs up the west side; the second branch turns onto the M1
  // corridor, which is what produces the parallel strokes from Cordwainer Lane west.
  const m4Trunk = run(P(480, 880), P(0, -60), [
    'Aldbury Vale',
    'Dunmore',
    'Weaver Street',
    'Hattersley',
    'Ferngate',
    'Netherfold',
    'Ash Hollow',
    'Cordwainer Lane',
    ['Cranbourne', { badges: ['step-free'] }],
  ])

  // -------------------------------------------------------------------------
  // The ring. Its last stop repeats its first, which is what makes it a ring: no
  // terminus, and so no route bullet stranded in the middle of the loop.
  // -------------------------------------------------------------------------

  const ringTop = run(P(360, 220), P(120, 0), [
    ['Chandlers Gate', { badges: ['step-free'] }],
    'Pomeroy',
    'Priory Fields',
    'Highgate Bar',
    'Templeton',
    'Marlowe Street',
    'Pargeter Hill',
  ])
  const ringRight = run(P(1080, 340), P(0, 120), ['Quarrymans', 'Eastgate', 'Bell Yard', 'Wrenbury'])
  const ringBottom = run(P(960, 700), P(-120, 0), [
    'Cobbleworth',
    'Longmarsh',
    'Sallow Bridge',
    'Kilnmore',
    'Hattersley',
    'Sedgeley',
  ])
  const ringLeft = run(P(360, 580), P(0, -120), ['Foundry Row', 'Guild Cross', 'Almsbury'])
  const ring = [...ringTop, ...ringRight, ...ringBottom, ...ringLeft, ringTop[0]]

  // -------------------------------------------------------------------------
  // Trams
  // -------------------------------------------------------------------------

  const t4Main = run(P(240, 820), P(80, 0), [
    'Millgate',
    'Bramblewick',
    'Turnstone',
    'Dunmore',
    'Cinderford',
    'Oakhanger',
    'Foundry Fields',
    'Sallow Row',
    ['Harbour Gate', { badges: ['ferry'] }],
    'Trencher Lane',
    'Salthouse',
    'Windlass',
    ['Skerry Point', { badges: ['ferry'] }],
  ])
  const t4Spur = [
    byName.get('Harbour Gate')!,
    ...run(P(880, 740), P(0, -80), ['Copperworks', 'Bell Quay']),
  ]

  const t5 = run(P(120, 220), P(0, 60), [
    'Kilnside',
    'Barrowfield',
    'Sculthorpe',
    'Ravenhurst',
    'Westgate',
    'Tolliver',
    ['Wharfedale', { badges: ['ferry'] }],
    'Fentiman',
    'Quarry End',
  ])

  // -------------------------------------------------------------------------
  // The later lines: a cross-city diagonal, a northern tram and a southern metro
  // -------------------------------------------------------------------------

  // Runs corner to corner, so it crosses almost everything else on the map. Most of
  // the bridges you can see at line crossings are this one passing over something.
  const m5 = run(P(180, 160), P(60, 60), [
    'Harrowgate',
    'Ninewells',
    'Claverton',
    'Almsbury',
    'Stonebridge',
    'Cordwainer Lane',
    'Amberley',
    'Fenchurch Row',
    'Kettleby',
    'Sallow Bridge',
    'Verdant Way',
    'Bowyers Lea',
  ])

  const t6 = run(P(120, 280), P(120, 0), [
    'Barrowfield',
    'Tannery Bank',
    'Whitmoor',
    'Corbridge',
    'Elmswood',
    'Pentland',
    'Ashfield Gate',
    'Sperring',
    'Nettlebed',
    'Hoxne',
  ])

  const m6 = run(P(240, 880), P(120, 0), [
    'Garrowby',
    'Sumpter Lane',
    'Aldbury Vale',
    'Thistlewood',
    'Aldbury South',
    'Ryehill',
    'Coalgate',
    'Fenmarsh',
    'Tidewell',
    ['Marlbrook', { badges: ['park-ride'] }],
  ])

  // A second heavy-rail route down the far west, sharing the T5 corridor for most of
  // its length — the longest parallel bundle on the map.
  const r3 = run(P(60, 100), P(0, 120), [
    'Westhaven',
    'Calder Bank',
    'Priorswood',
    'Ulverton',
    'Dellbridge',
    'Southmoor',
    ['Aldbury West', { badges: ['rail', 'park-ride'] }],
  ])

  // The southern orbital: heavy rail skirting the city, and the two feeders that
  // reach it. Nothing here touches the centre, which is what an orbital is for.
  const r4 = run(P(180, 940), P(120, 0), [
    ['Aldbury Parkway South', { badges: ['rail', 'park-ride'] }],
    'Willowdene',
    'Scarcroft',
    'Hedgerley',
    'Lambourne',
    ['Aldbury Junction', { badges: ['rail', 'step-free'] }],
    'Pickering',
    'Sowerby',
    'Marchwood',
    'Greetwell',
    ['Haverside', { badges: ['rail', 'park-ride'] }],
  ])

  const m7 = run(P(900, 160), P(0, 120), [
    'Fallowfield',
    'Cardingmill',
    'Peverel',
    'Wexcombe',
    'Ludgershall',
    'Braybrooke',
    'Netherwood',
  ])

  const t7 = run(P(1200, 220), P(0, 120), [
    'Ferrers Green',
    'Alderholt',
    'Crowmere',
    'Stainforth',
    'Wolvercote',
    'Skerry Point',
  ])

  const m8 = run(P(300, 160), P(0, 120), [
    'Carrickfell',
    'Bexwell',
    'Marston Gate',
    'Ullswater Road',
    'Pyrton',
    'Lowbank',
    'Heathermoor',
  ])

  // A funicular. Same mode as the cable car, different character — and it runs on a
  // timetable rather than continuously, which is what the service label is for.
  const k2 = [
    byName.get('Wolvercote')!,
    ...run(P(1260, 640), P(60, -60), ['Cliff Halt', 'Hanger Top']),
  ]

  // -------------------------------------------------------------------------
  // Buses — including one that only runs at night
  // -------------------------------------------------------------------------

  const byNames = (...names: string[]): StationId[] => names.map((n) => byName.get(n)!)

  const b12 = byNames(
    'Kilnside', 'Pomeroy', 'Chandlers Gate', 'Guild Cross',
    'Guild Square', 'Aldbury Central', 'Bishopsgate', 'Cobbleworth', 'Longmarsh',
  )
  const b20 = byNames('Aldbury Central', 'Exchange', 'Kings Wharf', 'Eastgate', 'Bell Yard', 'Harbour Gate')

  // -------------------------------------------------------------------------
  // Ferries along the estuary
  // -------------------------------------------------------------------------

  const f1 = byNames('Wharfedale', 'Kings Wharf', 'Harbour Gate', 'Skerry Point')
  const f2 = [byName.get('Kings Wharf')!, at(960, 580, 'Isle of Gull', { badges: ['ferry'] })]

  // -------------------------------------------------------------------------
  // Cable car up the escarpment, and a one-way airport shuttle loop
  // -------------------------------------------------------------------------

  const k1 = [
    byName.get('Pargeter Hill')!,
    ...run(P(1200, 160), P(60, -30), ['Beacon Halt', 'Aldbury Beacon']),
  ]

  const airportLoop = [
    byName.get('Eastfield')!,
    at(1260, 400, 'Airport Approach'),
    at(1260, 340, 'Aldbury Airport', {
      badges: ['airport', 'rail', 'step-free'],
      nameSecondary: 'Maes Awyr',
    }),
    at(1320, 400, 'Airport Cargo'),
    byName.get('Eastfield')!, // closes the loop, and it only runs one way round
  ]

  const id = (name: string): StationId => byName.get(name)!
  const branch = (stops: StationId[], extra: Partial<Branch> = {}): Branch =>
    makeBranch(newBranchId(), stops, extra)

  const line = (name: string, mode: string, color: string, branches: Branch[]): Line => ({
    id: newLineId(),
    name,
    mode,
    color,
    branches,
    bends: {},
    hidden: false,
  })

  const lines: Line[] = [
    // Heavy rail first, so it sits under the metro where they share a corridor.
    line('R1', 'rail', '#1B4F9C', [branch(railStops, { name: 'all stations' })]),

    // The express. It calls at five of R1's stations and RUNS THROUGH the rest, which
    // is why it follows the same alignment instead of cutting a straight line across
    // the map. You cannot board it where it does not stop.
    line('R2', 'rail', '#A8143C', [
      branch(
        [
          id('Aldbury Parkway'),
          id('Norbridge'),
          id('Aldbury North'),
          id('Ravensmoor'),
          id('Eastmarch'),
        ],
        {
          name: 'express',
          service: 'Peak only',
          passes: [
            id('Fenwick'),
            id('Hollowmere'),
            id('Stanmoor'),
            id('Kestrel Hill'),
            id('Thornleigh'),
            id('Whitcombe'),
          ],
        },
      ),
    ]),

    line('M1', 'metro', '#C9342B', [branch(m1)]),
    line('M2', 'metro', '#00639B', [branch(m2)]),
    line('M3', 'metro', '#00784F', [branch(m3)]),

    // A Y, with the western branch given its own colour the way the Northern line's
    // are distinguished on some maps.
    line('M4', 'metro', '#6B4796', [
      branch(m4Trunk, { name: 'to Cranbourne' }),
      branch(
        byNames('Cordwainer Lane', 'Saltmarket', 'Guild Cross', 'Fairholme', 'Brackenfield', 'Alder Row', 'Westgate'),
        { name: 'to Westgate', color: '#8C4A00' },
      ),
    ]),

    // The ring.
    line('C1', 'metro', '#D4A017', [branch(ring, { name: 'circle' })]),

    line('T4', 'tram', '#2E7D6B', [
      branch(t4Main, { name: 'Skerry Point' }),
      branch(t4Spur, { name: 'Longmarsh' }),
    ]),
    line('T5', 'tram', '#4B6A16', [branch(t5)]),
    line('T6', 'tram', '#8C4A00', [branch(t6)]),

    line('M5', 'metro', '#A8143C', [branch(m5)]),
    line('M6', 'metro', '#5C5F66', [branch(m6)]),

    line('R3', 'rail', '#12557A', [branch(r3, { name: 'west coast' })]),
    line('R4', 'rail', '#4B6A16', [branch(r4, { name: 'southern orbital' })]),

    line('M7', 'metro', '#B3187C', [branch(m7)]),
    line('T7', 'tram', '#0D7C93', [branch(t7)]),

    line('B12', 'bus', '#B45A0E', [branch(b12)]),
    line('N20', 'bus', '#5C5F66', [branch(b20, { service: 'Nights only' })]),

    line('F1', 'ferry', '#0D7C93', [branch(f1)]),
    line('F2', 'ferry', '#12557A', [branch(f2)]),

    line('M8', 'metro', '#2E7D6B', [branch(m8)]),

    line('K1', 'cable', '#7A2E8E', [branch(k1)]),
    line('K2', 'cable', '#D4A017', [branch(k2, { name: 'funicular', service: 'Apr–Oct' })]),

    // One way round only: the shuttle leaves Eastfield, calls at the terminal and the
    // cargo gate, and comes back to Eastfield. Ask the planner for the reverse and it
    // sends you round the loop rather than back up the way you came.
    line('A1', 'bus', '#B3187C', [
      branch(airportLoop, { name: 'airport loop', direction: 'forward', service: 'Every 10 min' }),
    ]),
  ]

  // -------------------------------------------------------------------------
  // Terrain
  // -------------------------------------------------------------------------

  const terrain: Terrain[] = [
    // The estuary: a wandering trace over the map, simplified to four strokes for the
    // diagram — the move that separates a transit map from a drawing on a screenshot.
    makeTerrain(newTerrainId(), 'waterway', {
      name: 'River Ald',
      geo: [
        { x: 40, y: 640 }, { x: 180, y: 672 }, { x: 320, y: 628 }, { x: 470, y: 686 },
        { x: 620, y: 640 }, { x: 780, y: 700 }, { x: 940, y: 648 }, { x: 1120, y: 706 },
        { x: 1340, y: 660 },
      ],
      schematic: [
        { x: 40, y: 620 }, { x: 520, y: 620 }, { x: 640, y: 740 }, { x: 1360, y: 740 },
      ],
    }),

    // A lake with an island in it — the case a single ring cannot express.
    makeTerrain(newTerrainId(), 'water', {
      name: 'Gull Water',
      closed: true,
      fill: 'solid',
      geo: [{ x: 880, y: 520 }, { x: 1060, y: 520 }, { x: 1060, y: 640 }, { x: 880, y: 640 }],
      schematic: [{ x: 880, y: 520 }, { x: 1060, y: 520 }, { x: 1060, y: 640 }, { x: 880, y: 640 }],
      holes: [
        {
          geo: [{ x: 930, y: 556 }, { x: 1000, y: 556 }, { x: 1000, y: 606 }, { x: 930, y: 606 }],
          schematic: [{ x: 930, y: 556 }, { x: 1000, y: 556 }, { x: 1000, y: 606 }, { x: 930, y: 606 }],
        },
      ],
    }),

    makeTerrain(newTerrainId(), 'green', {
      name: 'Pentland Common',
      closed: true,
      fill: 'hatch',
      geo: [{ x: 540, y: 220 }, { x: 700, y: 220 }, { x: 700, y: 360 }, { x: 540, y: 360 }],
      schematic: [{ x: 540, y: 250 }, { x: 690, y: 250 }, { x: 690, y: 370 }, { x: 540, y: 370 }],
    }),
    makeTerrain(newTerrainId(), 'green', {
      name: 'Beacon Down',
      closed: true,
      fill: 'hatch',
      geo: [{ x: 1180, y: 60 }, { x: 1360, y: 60 }, { x: 1360, y: 200 }, { x: 1180, y: 200 }],
      schematic: [{ x: 1180, y: 60 }, { x: 1360, y: 60 }, { x: 1360, y: 200 }, { x: 1180, y: 200 }],
    }),

    makeTerrain(newTerrainId(), 'builtup', {
      name: 'Dockside',
      closed: true,
      fill: 'stipple',
      geo: [{ x: 760, y: 760 }, { x: 1120, y: 760 }, { x: 1120, y: 880 }, { x: 760, y: 880 }],
      schematic: [{ x: 760, y: 770 }, { x: 1120, y: 770 }, { x: 1120, y: 880 }, { x: 760, y: 880 }],
    }),

    makeTerrain(newTerrainId(), 'boundary', {
      name: 'City limit',
      closed: true,
      fill: 'none',
      geo: [{ x: 20, y: 40 }, { x: 1400, y: 40 }, { x: 1400, y: 1000 }, { x: 20, y: 1000 }],
      schematic: [{ x: 20, y: 40 }, { x: 1400, y: 40 }, { x: 1400, y: 1000 }, { x: 20, y: 1000 }],
    }),

    // Fare zones, drawn behind everything. Station `zone` values match these names.
    makeTerrain(newTerrainId(), 'zone', {
      name: 'Zone 1',
      zone: '1',
      closed: true,
      fill: 'solid',
      geo: [{ x: 380, y: 210 }, { x: 1060, y: 210 }, { x: 1060, y: 710 }, { x: 380, y: 710 }],
      schematic: [{ x: 380, y: 210 }, { x: 1060, y: 210 }, { x: 1060, y: 710 }, { x: 380, y: 710 }],
    }),
    makeTerrain(newTerrainId(), 'zone', {
      name: 'Zone 2',
      zone: '2',
      closed: true,
      fill: 'none',
      geo: [{ x: 90, y: 130 }, { x: 1350, y: 130 }, { x: 1350, y: 910 }, { x: 90, y: 910 }],
      schematic: [{ x: 90, y: 130 }, { x: 1350, y: 130 }, { x: 1350, y: 910 }, { x: 90, y: 910 }],
    }),

    // Free annotations, each styled differently — the thing a single hardcoded text
    // size could never do.
    makeTerrain(newTerrainId(), 'label', {
      name: 'RIVER ALD',
      geo: [{ x: 240, y: 612 }],
      schematic: [{ x: 250, y: 606 }],
      text: { size: 19, italic: true, color: '#3E7E96', letterSpacing: 3, opacity: 0.75, align: 'start' },
    }),
    makeTerrain(newTerrainId(), 'label', {
      name: 'BEACON DOWN',
      geo: [{ x: 1270, y: 132 }],
      schematic: [{ x: 1270, y: 132 }],
      text: { size: 13, weight: 700, color: '#4B6A16', opacity: 0.7, letterSpacing: 2 },
    }),
    makeTerrain(newTerrainId(), 'label', {
      name: 'DOCKSIDE',
      geo: [{ x: 940, y: 828 }],
      schematic: [{ x: 940, y: 834 }],
      text: { size: 15, weight: 600, opacity: 0.45, letterSpacing: 4 },
    }),
    makeTerrain(newTerrainId(), 'label', {
      name: 'to the coast →',
      geo: [{ x: 1300, y: 706 }],
      schematic: [{ x: 1300, y: 782 }],
      text: { size: 12, italic: true, opacity: 0.6, align: 'end' },
    }),
  ]

  // -------------------------------------------------------------------------
  // Furniture
  // -------------------------------------------------------------------------

  const place = (what: Placement['what'], p: Vec2, label?: string): Placement => ({
    id: newPlacementId(),
    what,
    geo: { ...p },
    schematic: { ...p },
    scale: 1,
    angle: 0,
    opacity: 1,
    locked: false,
    hidden: false,
    label,
  })

  // Furniture goes in the margin, outside everything the network occupies. A legend
  // dropped in the middle of the map covers the very thing it is explaining.
  const placements: Placement[] = [
    place({ kind: 'legend' }, { x: 2320, y: 760 }, 'Lines'),
    place({ kind: 'titleBlock' }, { x: 420, y: 60 }, 'Aldbury'),
    place({ kind: 'northArrow' }, { x: 2320, y: 140 }),
    place({ kind: 'scaleBar' }, { x: 2320, y: 260 }, '2 km'),
  ]

  // Out-of-station interchanges: places where the map has to say "leave and walk",
  // which no amount of drawing two lines through one dot can express.
  const transfers = [
    { a: id('Kings Wharf'), b: id('Wexcombe'), note: '5 min walk' },
    { a: id('Guild Cross'), b: id('Chandlers Gate'), note: '4 min walk' },
    { a: id('Peartree'), b: id('Oakhanger'), note: '3 min walk' },
  ].map((t) => ({ id: newTransferId(), ...t, hidden: false }))

  // Everything above is laid out on a 60-unit grid, which keeps the coordinates
  // readable and the intersections exact. It is then scaled up as a whole.
  //
  // The reason is label collisions: type size is fixed in map units, so spreading the
  // stations apart makes every name relatively smaller and gives the placement engine
  // room to work. At the authoring grid the centre of the city was unreadable.
  const SPREAD = 1.5
  const grow = (v: Vec2): Vec2 => ({ x: Math.round(v.x * SPREAD), y: Math.round(v.y * SPREAD) })

  for (const st of stations) {
    st.geo = grow(st.geo)
    st.schematic = grow(st.schematic)
  }
  for (const t of terrain) {
    t.geo = t.geo.map(grow)
    t.schematic = t.schematic.map(grow)
    t.holes = t.holes.map((h) => ({ geo: h.geo.map(grow), schematic: h.schematic.map(grow) }))
  }

  return {
    ...base,
    stations,
    lines,
    terrain,
    placements,
    transfers,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
}
